//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EmployeeInformationSystem.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;
    using System.Web;

    public partial class Employee
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Employee()
        {
            this.Salaries = new HashSet<Salary>();
        }
    
        public int EmployeeID { get; set; }

        //Required Valitation
        [Required(ErrorMessage = "Enter Employee Name")]
        public string EmployeeName { get; set; }
        public Nullable<int> BranchName { get; set; }
        public Nullable<int> DepartmentName { get; set; }


        //Regular Expression Valitation
        [Required(ErrorMessage = "Enter Employee Valid Email")]
        public string Email { get; set; }

        //Compare Valitation
        [Compare("Email", ErrorMessage = "Your Email Doesnot Matched!!!")]
        public string ConfirmEmail { get; set; }

        //Range Validation

        [Required(ErrorMessage = "Enter Cellphone No.")]
        [MaxLength(11,ErrorMessage ="Contact Number Must be greater than 11 Digit")]
        [MinLength(11, ErrorMessage = "Contact Number Can't be less than 11 Digit")]
        public string CellPhone { get; set; }

        [DataType(DataType.Date)]
        [DisplayFormat(ApplyFormatInEditMode = true, DataFormatString = "{0:d}")]
        //[DisplayFormat(ApplyFormatInEditMode = true, DataFormatString = "{0: dd-MM-yyyy HH:mm}")]
        public Nullable<System.DateTime> DOB { get; set; }
        public string EmployeeImage { get; set; }

        [NotMapped]
        public HttpPostedFileBase UploadImage { get; set; }

        public virtual Branch Branch { get; set; }
        public virtual Department Department { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Salary> Salaries { get; set; }
    }
}
